package projeto_estatistica;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DANIEL
 */
public class TabelaFinal extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Cliente
     */
    double totalgeral = 0, c, somatoriotrat, somatoriox2;
    int tratamentos = 4, repetiçoes = 4, numero = 0;

    public TabelaFinal(int tratamentos, int repetiçoes, double totalgeral, double c, double somatoriotrat, double somatoriox2, int numero) {
        this.tratamentos = tratamentos;
        this.repetiçoes = repetiçoes;
        this.totalgeral = totalgeral;
        this.c = c;
        this.somatoriotrat = somatoriotrat;
        this.somatoriox2 = somatoriox2;
        this.numero = numero;
        initComponents();

        //setIconImage(new ImageIcon("src\\Icons\\icon_C_Movie.png").getImage());
        iniciar();
        /*jTable.setColumnSelectionAllowed(true);
         jTable.setRowSelectionAllowed(true);
         jTable.setSurrendersFocusOnKeystroke(true);
         */

        //ajustarcolunas();
    }

    public void iniciar() {
        setLocationRelativeTo(null);
        JTableHeader cabecalho = jTable.getTableHeader();
        cabecalho.setFont(new Font("Tahoma", 1, 16));
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("FV");
        dtm.addColumn("GL");
        dtm.addColumn("SQ");
        dtm.addColumn("QM");
        dtm.addColumn("F");
        double sqtrat = (1.0 / repetiçoes * somatoriotrat - c);
        double gltrat = tratamentos - 1;
        double qmtrat = (sqtrat / (tratamentos - 1.0));
        double glres = numero - tratamentos;
        double totalsq = somatoriox2 - c;
        double sqres = totalsq - sqtrat;
        double qmres = sqres / glres;
        int gltotal = numero - 1;
        double ftrat = qmtrat / qmres;
        final String f = "*";
        dtm.addRow(new Object[]{"TRAT", "" + gltrat, "" + sqtrat, "" + qmtrat, "" + ftrat});
        dtm.addRow(new Object[]{"RES", "" + glres, "" + sqres, "" + qmres, "" + f});
        dtm.addRow(new Object[]{"TOTAL", "" + gltotal, "" + totalsq, "", ""});
        jTable.setModel(dtm);

        DefaultTableCellRenderer alterar = new DefaultTableCellRenderer() {
            public void setValue(Object value) {
                if (!value.equals("*") && !value.equals("n.s.")) {
                    setToolTipText("");
                    System.out.println("valor: " + value);
                } else {
                    if (value.equals("*")) {
                        setToolTipText("" + value);
                    } else {
                        setToolTipText("" + value);
                    }

                    System.out.println("valor: " + value);
                }
                System.out.println("value: " + value);
                setHorizontalAlignment(JLabel.CENTER);
                super.setValue(value);
            }
        };
        jTable.getColumn("F").setCellRenderer(alterar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Criar Projeto");
        setResizable(false);

        jTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Valor", "Vencimento", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setAutoscrolls(false);
        jTable.setCellSelectionEnabled(true);
        jTable.setFillsViewportHeight(true);
        jTable.setSelectionBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        jTable.getTableHeader().setResizingAllowed(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getColumn(0).setResizable(false);
        jTable.getColumnModel().getColumn(2).setResizable(false);
        jTable.getColumnModel().getColumn(3).setResizable(false);
        jTable.getColumnModel().getColumn(4).setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 374, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(230, 230, 230))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        //
    }//GEN-LAST:event_jTableMouseClicked

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        //
    }//GEN-LAST:event_jTableMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable.setFocusable(true);
        boolean preenchidos = true;
        for (int i = 1; i < tratamentos; i++) {
            for (int j = 1; j <= repetiçoes + 1; j++) {
                if (jTable.getValueAt(i, j).equals("")) {
                    preenchidos = false;
                }
            }
        }
        if (preenchidos) {
            boolean criou = false;
            while (!criou) {
                String nomeprojeto = JOptionPane.showInputDialog(null, "Digite nome do projeto: ");
                if (!nomeprojeto.equals("")) {
                    File diretorio = new File("C:/Projeto/");
                    File projeto = new File("C:/Projeto/" + nomeprojeto + ".txt");
                    if (!diretorio.exists()) {
                        diretorio.mkdirs();
                        criou = criarArquivo(projeto, nomeprojeto);
                    } else {
                        criou = criarArquivo(projeto, nomeprojeto);

                    }
                } else {
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todas as células.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        totalgeral = Double.parseDouble("" + jTable.getValueAt(tratamentos, repetiçoes + 1));
        numero = tratamentos * repetiçoes;
        c = (totalgeral * totalgeral) / numero;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        if (sair == 0) {
            ProjetoEstatistica p = new ProjetoEstatistica();
            p.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public boolean criarArquivo(File projeto, String nomeprojeto) {
        if (projeto.exists()) {
            int i = JOptionPane.showOptionDialog(null, "Projeto já existe, deseja sobrescrever?", "Ja existe", 1, 1, null, null, null);
            if (i == 0) {
                salvar("C:/Projeto/" + nomeprojeto + ".txt");
                return true;
            }
            return false;
        } else {
            try {
                new File("C:/Projeto/" + nomeprojeto + ".txt").createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(TabelaFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
            salvar("C:/Projeto/" + nomeprojeto + ".txt");

            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // try {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*UIManager.setLookAndFeel(new AluminiumLookAndFeel());
         } catch (UnsupportedLookAndFeelException ex) {
         Logger.getLogger(Locadora.class.getName()).log(Level.SEVERE, null, ex);
         }/*
         //</e
         //</editor-fold>

         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaFinal(3, 3, 1.0, 1.0, 1.0, 1.0, 1).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    //Formata resultado com duas casas decimais

    public String format(double x) {
        return String.format("%.2f", x);
    }

    private void salvar(String caminho) {
        FileWriter fw;
        try {
            fw = new FileWriter(caminho);
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < tratamentos; i++) {
                for (int j = 1; j <= repetiçoes; j++) {
                    System.out.println("" + jTable.getValueAt(i, j));
                    bw.write("" + jTable.getValueAt(i, j) + " ");
                }
                System.out.println("");
                if (i != tratamentos - 1) {
                    bw.write("@");
                }
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(TabelaFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }
}
